version: "3.9"

services:
  nginx:
    container_name: mapsential_nginx
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=8000
    depends_on:
      - "rest_api"
      - "admin_backend"
      - "frontend"

  frontend:
    container_name: mapsential_frontend
    build:
      context: ./mapsential-frontend

  rest_api:
    container_name: mapsential_rest_api
    build:
      context: ./rest-api
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  swagger_ui:
    container_name: mapsential_swagger_ui
    build:
      context: ./swagger-ui
    ports:
      - "8120:8120"
    depends_on:
      - "rest_api"

  admin_backend:
    container_name: mapsential_admin_backend
    build:
      context: .
      dockerfile: ./admin-backend/Dockerfile
    volumes:
      - ./admin-backend:/usr/src/admin-backend
      - ./db:/usr/src/db
    ports:
      - "8090:8090"
    depends_on:
      - "db"
    environment:
      - ENV=docker-dev

  db:
    container_name: mapsential_db
    image: "postgres"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password