version: "3.9"

services:
  nginx:
    container_name: mapsential_nginx
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    depends_on:
      - "rest_api"
      - "admin_backend"
      - "frontend"

  frontend:
    container_name: mapsential_frontend
    build:
      context: ./mapsential-frontend
    ports:
      - "8100:8100"

  rest_api:
    container_name: mapsential_rest_api
    build:
      context: .
      dockerfile: ./backend/api.Dockerfile
    volumes:
      - ./backend:/usr/src/backend
      - ./db:/usr/src/db
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - ENV=docker-dev

  admin_backend:
    container_name: mapsential_admin_backend
    build:
      context: .
      dockerfile: ./backend/admin.Dockerfile
    volumes:
      - ./backend:/usr/src/backend
      - ./db:/usr/src/db
    ports:
      - "8090:8090"
    depends_on:
      - "db"
    environment:
      - ENV=docker-dev

  db:
    container_name: mapsential_db
    image: "postgres"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password