version: "3.9"

services:
  nginx:
    volumes:
      - ./nginx/nginx.docker-dev.conf:/etc/nginx/nginx.conf:ro

  rest_api:
    volumes:
      - ./docker_dev_plaintext_secrets/postgres/password.txt:/run/secrets/postgres_password

  swagger_ui:
    build: 
      args:
        - node_version=17

  admin_backend:
    volumes:
      - ./docker_dev_plaintext_secrets/postgres/password.txt:/run/secrets/postgres_password

  db:
    volumes:
      - ./docker_dev_plaintext_secrets/postgres/password.txt:/run/secrets/postgres_password
