version: "3.9"

services:
  nginx:
    container_name: mapsential_nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=8000
    depends_on:
      - "rest_api"
      - "admin_backend"
      - "frontend"

  frontend:
    container_name: mapsential_frontend
    build:
      context: ./mapsential-frontend
    ports:
      - "8100:8100"

  rest_api:
    container_name: mapsential_rest_api
    build:
      context: ./rest-api
    ports:
      - "8080:8080"
    secrets:
      - postgres_password
    depends_on:
      - "db"

  swagger_ui:
    container_name: mapsential_swagger_ui
    build:
      context: ./swagger-ui
    ports:
      - "8120:8120"
    depends_on:
      - "rest_api"

  admin_backend:
    container_name: mapsential_admin_backend
    build:
      context: .
      dockerfile: ./admin-backend/Dockerfile
    volumes:
      - ./admin-backend:/usr/src/admin-backend
      - ./db:/usr/src/db
    ports:
      - "8090:8090"
    secrets:
      - postgres_password
    depends_on:
      - "db"

  db:
    container_name: mapsential_db
    image: "postgres"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password

#  airflow:
#    container_name: mapsential_airflow
#    build:
#      context: .
#      dockerfile: ./airflow.Dockerfile
#      args:
#        - PY_VERSION=3.9
#        - AIRFLOW_HOME=/opt/airflow
#        - AIRFLOW_VERSION=2.1.4
#    volumes:
#      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
##      - ./airflow/webserver_config.py:/opt/airflow/webserver_config.py
#      - ./airflow/dags:/opt/airflow/dags
#      - ./airflow/logs:/opt/airflow/logs
#      - ./airflow/plugins:/opt/airflow/plugins
#    ports:
#      - "8081:8080"
#    secrets:
#      - email_clemens
#      - email_denis
#      - email_lucas
#      - email_orhun
#      - email_oscar
#      - airflow_password_clemens
#      - airflow_password_denis
#      - airflow_password_lucas
#      - airflow_password_orhun
#      - airflow_password_oscar

secrets:
  postgres_password:
    external: true
  email_clemens:
    external: true
  email_denis:
    external: true
  email_lucas:
    external: true
  email_orhun:
    external: true
  email_oscar:
    external: true
  airflow_password_clemens:
    external: true
  airflow_password_denis:
    external: true
  airflow_password_lucas:
    external: true
  airflow_password_orhun:
    external: true
  airflow_password_oscar:
    external: true
