files: ^backend/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        files: admin_backend/.*
      - id: trailing-whitespace
  # Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
        args: ['--config-file=./backend/mypy.ini']
        additional_dependencies: ['types-requests']
  # Reorder imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
  - repo: local
    hooks:
      # Dead code
      - id: vulture
        name: check for dead code using vulture
        entry: ./backend/check-dead-code.sh
        language: script
      # Vulnerabilities
      - id: pipenv-check
        name: check pipenv dependencies for python vulnerabilities using PyUp
        entry: pipenv check
        language: system
      # Tests
      - id: tests
        name: run tests
        entry: backend/test.sh
        pass_filenames: false
        language: script
